### PR TITLE
Prevent the special items from being moved

### PR DESCRIPTION
**Pull request by HSGamer**
They may interact with the off-hand item.

### CODE REVIEW

**Comment by montlikadani** [comment]
Instead, we could do this by preventing items from swapping in the inventory with `PlayerSwapHandItemsEvent`. This should be implemented in a separate class so that there are no conflicts and exceptions on 1.8 due to non-existent events.

**Comment by HSGamer** [comment]
One more case is that the player may move the item to his offhand when he opens his inventory.

**Comment by HSGamer** [comment]
I think this is simpler.
One other way is to cancel `PlayerSwapHandItemsEvent` and `InventoryClickEvent` for special items. But I think that is complicated.

**Comment by montlikadani** [comment]
> One more case is that the player may move the item to his offhand when he opens his inventory.

There is an event called `InventoryDragEvent` which listens to item dragging in specific inventories.

**Comment by HSGamer** [comment]
I didn't test it as my test server is on 1.12.2

**Comment by HSGamer** [comment]
This should be enough

**Pull request merged**
