### PR TITLE
Fix game signs not work in 1.14

### PR DESCRIPTION
**Pull request by montlikadani**
I fixed this, because I found the solution, tested in my plugin, and it works.

### CODE REVIEW

**Comment by Plajer** [comment]
Not applicable for 1.13 API

**Comment by montlikadani** [comment]
Because this changes is only for 1.14+ versions: https://github.com/Plajer-Lair/Village_Defense/pull/29/files#diff-4e3a273dbd8299f20784ac3ba7c9019eR211

**Comment by Plajer** [comment]
can't use 1.14 api on 1.13 spigot

**Comment by montlikadani** [comment]
Wut?? Because the maven not refreshed and not detect 1.14 api. Make sure you have refreshed and using the latest spigot 1.14 from BuildTools.

**Pull request merged**
