### PR TITLE
option to fetch the profile for the player profile

### PR DESCRIPTION
**Pull request by HSGamer**
Some builds of Spigot / Paper cause the server to be delayed when loading player profiles for player heads.

### CODE REVIEW

**Comment by montlikadani** [comment]
That is why we do that in asynchronous operation, [here](https://github.com/Plugily-Projects/Commons-Box/blob/development/Commons%20Box%20Minecraft/src/main/java/pl/plajerlair/commonsbox/minecraft/compat/VersionUtils.java#L104-L110). In this case, the `join()` method is an implementation of `CompletableFuture`, apparently a "thread blocker" that blocks the main thread until it is done. The only way to avoid blocking the main thread is to remove the `join` method, of course in the Common-Box module, and instead do it in the method as well as in other projects (if it exists) with the `thenAccept` method. I mean, to give the method a return value so we can use Future implementations.

Adding a configuration option is not the right decision in this PR implementation, as it can break between users and they don’t know what to do and ask for help unnecessarily.

**Comment by HSGamer** [comment]
weirdly, it's not the reason in my case.
My case is `setOwningPlayer` on the latest Paper 1.16.5
https://pastebin.com/H79PyB7A

**Comment by HSGamer** [comment]
I saw the issue now...
The detector for the 1.16.X is not working...
I will push a commit on that soon...

**Comment by montlikadani** [comment]
I guess we have to perform `setOwningPlayer` method in async operation too. There is no point in adding a configuration option.

> The detector for the 1.16.X Paper is not working...

Detector? 😅

**Comment by HSGamer** [comment]
:laughing:

**Comment by HSGamer** [comment]
Well... the `detector` is also not the reason...
I think we have to do that...
> I guess we have to perform `setOwningPlayer` method in async operation too. There is no point in adding a configuration option.
> 
> > The detector for the 1.16.X Paper is not working...
> 
> Detector?

**Comment by HSGamer** [comment]
https://github.com/Plugily-Projects/Commons-Box/pull/4

**Pull request closed without merging**
